name: Ejecutar Job Según Selección

on:
  push:
  workflow_dispatch:
    inputs: 
      language: 
        required: true
        default: 'Scala'
        description: Please select the FW action
        type: choice
        options:
        - Scala
        - Python

jobs:
  seleccionar_y_ejecutar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v2

      - name: Seleccionar y Ejecutar
        run: |
          echo ${{ github.event.inputs.language }}
