name: Publish Snapshot

on:
  push:
    branches:
      "master"

jobs:
  seleccionar_y_ejecutar:
    name: Publishing snapshot for ${{ github.event.inputs.language }}
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v2

