name: Publish Snapshot

on:
  workflow_dispatch:
    inputs: 
      language: 
        required: true
        default: 'Scala'
        description: Select protos lang version
        type: choice
        options:
        - Scala
        - Python

jobs:
  seleccionar_y_ejecutar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v2

      - name: Seleccionar y Ejecutar
        run: |
          echo ${{ github.event.inputs.language }}
